### ISSUE TITLE
Upgrade Tailwind to ^1.0

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/jigsaw-docs-template#27]
(See https://github.com/tightenco/jigsaw-site/issues/51)

**Comment by cameron-elliott** [comment]
What tool would you guys use to do some CSS linting? I have a trial tool which commercial for Visual Studio, which is pretty nice, but I am wondering if there is an OSS tool which is similar.
This tool highlights the old 0.74 tags in the HTML which are no longer defined in 1.x. (Resharper)

**Comment by mattstauffer** [comment]
@cameron-elliott When I've upgraded other sites, I've primarily relied just on walking through the upgrade guide:

https://tailwindcss.com/docs/upgrading-to-v1/

Not sure if there's anything OS that's similar, but there definitely could be!

**Comment by cameron-elliott** [comment]
I would like to ask/confirm that the maintainers are open to a PR from myself (a non-maintainer), as long as the PR seems of sufficient quality for this issue?
(I understand it is a good idea to propose changes before submitting PRs)

-- details --

So, I am actively taking a stab at this. I wrote @damiani about whether he might be interested in a small amount of consulting to work on this, but I would suspect he is busy with many projects.
(I hope you didn't mind, @damiani )

I am carefully reviewing Andypa's original commits to the 'blog' repo, and Damiani's commits also so I can offer hopefully a pretty good PR. I am also chunking my commits fairly small and keeping a detailed set of notes.

I am an experienced non-web developer, so this is going a bit slow, but it's kind of a cool learning experience for Tailwind and Jigsaw, anyways! 

My two main tools for validating my success, are 1) of course the responsive visuals of my 1.x attempt compared to the responsive visuals of the original 0.7.2, and 2) a tool to show me unused CSS classes in Html (a crude measure of progress, but a useful double-check).

I am totally open to ideas and suggestions from the Tighten team on nailing this.

Thanks,
Cameron

**Comment by mattstauffer** [comment]
Hey @cameron-elliott, we are *more* than happy for your help, and we absolutely love working with new folks as they get comfortable with the various aspects of our tech stack. I'm so excited to see your work and we'll absolutely work with you to get everything perfect.

@damiani is out for a while but i'll be happy to help in the interim.

**Comment by cameron-elliott** [comment]
Hey @mattstauffer, I got a question for you.
Should files under ./source/assets/build/ be checked into git ?
[seems like maybe they shouldn't be]

There is nothing there in the 'blog' repo, but there are some files in the 'docs' repo,
and it seems like the files under ./source/assets/build get built at 'init' time anyway.

It may not be a big deal either way, but I am carefully commiting each change, so I want to understand all the files showing up in my 'git status' list.
What do you think, should these be removed and gitignored?

Experimented some more, these are generated, and this comment backs up my perspective: https://stackoverflow.com/a/32689241 "Any generated content should not, if possible, be included in a git repo (and pushed)"

So, I am removing this stuff until someone else says otherwise (in the PR/my-repo)

**Comment by mattstauffer** [comment]
@cameron-elliott yah I *think* they should be gone. Let's drop em. We can add back if we're missing something.

**Comment by jasonlbeggs** [comment]
@cameron-elliott did you ever finish the PR for this or are you open to someone else taking over the upgrade? Thanks!

**Comment by cameron-elliott** [comment]
@jasonlbeggs good news! It is done and in!
Pull request: #28 

Also, it may or may not be of use to you, but I thought I'd mention it,
I also submitted a PR for a merged blog/docs template: Pull request: #30 
(since for my project I wanted both docs+blog together)

I would be really curious about whether it suits your use case or not, and
and feedback or ideas you would have.

Again, a kudos to the Tighten guys, and the designers on these templates, I have been working on my yet unreleased site, and I am so glad and appreciative to all of you created these quality open-source templates, tools and designs. 🎉

**Comment by jasonlbeggs** [comment]
Ok sweet! Thanks for doing that.

@mattstauffer this PR can be closed.
